### PR TITLE
Partial Ext. Storage Support + Typo Fix

### PR DESCRIPTION
**Pull request by fuzun**
Partial support for external storage utilization for higher api levels.
Needs some fix to show correct path to the user.

### CODE REVIEW

**Comment by fuzun** [comment]
I tested this build and managed to start half-life which is in extSdCard. But only without "-dev" in parameters.

If I put '-dev' in parameter textbox, xash3d crashed or showed a error messagebox.

I really dont know whether this build made it to run a game which is located in sd card or not. Nonetheless this is only a partial support and some extra coding must be done to make it fully supported.

**Comment by fuzun** [comment]
Correction of previous post;
If I use both '-dev' and '-log' at the same time, it crash.
Only '-dev' -> no problem.
Only '-log' -> no problem.

I did some research and find this:
`
	if( Sys_CheckParm( "-log" ) && host.developer != 0 )
	{
		s_wcd.log_active = true;
		Q_strncpy( s_wcd.log_path, "engine.log", sizeof( s_wcd.log_path ));
	}
`
Application crashes when both parameters are used because it can not write to engine.log.

`
	if( s_wcd.log_active )
	{
		s_wcd.logfile = fopen( s_wcd.log_path, mode );
		if( !s_wcd.logfile ) MsgDev( D_ERROR, "Sys_InitLog: can't create log file %s\n", s_wcd.log_path );
		else s_wcd.logfileno = fileno( s_wcd.logfile );

		fprintf( s_wcd.logfile, "================================================================================\n" );
		fprintf( s_wcd.logfile, "\t%s (build %i) started at %s\n", s_wcd.title, Q_buildnum(), Q_timestamp( TIME_FULL ));
		fprintf( s_wcd.logfile, "================================================================================\n" );
	}
`

I think it should write the log file to its own data directory (Android/data) instead of game resource directory.

**Comment by fuzun** [comment]
And It can not save or even load save files in this situation.

**Comment by a1batross** [comment]
I think we shouldn't go outside "xash" folder at all. (except loading PAK files from APK assets)
Less Android code in engine == happy crossplatform engine.

Better idea is to request permission to whole sdcard(other apps do same thing) on first run.

**Comment by fuzun** [comment]
It takes requested permissions for that specific game resource directory(I dont think it is a good idea to take permissions for whole external storage) with this:
`getContentResolver().takePersistableUriPermission`
And as we have to use this content resolver api to request permissions, target api level must be 19 or more.

But the problem is that this code is not enough. We need to dig into xash3d and put some if checks for android system and then make it open a file with file descriptor instead of file location.

**Comment by mittorn** [comment]
But accessing whole sd card is more combatible way. The big broblem is that we cannot correctly determine, which storage was selected and only can get relative path.
But when we accessing whole card, we can just ask user to choose root folder of external memory.
My device has not this restriction (Android 5.0+ is availiable only as custom roms), so i cannot check it.

**Comment by fuzun** [comment]
Closing now, will investigate further.

**Pull request closed without merging**
